version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./batch.sql:/docker-entrypoint-initdb.d/batch.sql
    ports:
      - '5432:5432'
  web-app:
    image: aldeebob/swarm-server
    depends_on:
      - db
    ports:
      - '3000:3000'
networks:
  default:
    external:
        name: swarmy